with open("numar.txt", "r") as f:
    n=int(f.read())
a=(str(n) + "* 1" +" = "+ str(n*1))
b=(str(n) + "* 2" +" = "+ str(n*2))
c=(str(n) + "* 3" +" = "+ str(n*3))
d=(str(n) + "* 4" +" = "+ str(n*4))
e=(str(n) + "* 5" +" = "+ str(n*5))
r=(str(n) + "* 6" +" = "+ str(n*6))
g=(str(n) + "* 7" +" = "+ str(n*7))
h=(str(n) + "* 8" +" = "+ str(n*8))
i=(str(n) + "* 9" +" = "+ str(n*9))
l=(str(n) + "* 10" +" = "+ str(n*10))
with open("inmultire.txt", "w") as f:
   f.write(str(a))
   f.write("\n")
   f.write(str(b))
   f.write("\n")
   f.write(str(c))
   f.write("\n")
   f.write(str(d))
   f.write("\n")
   f.write(str(e))
   f.write("\n")
   f.write(str(r))
   f.write("\n")
   f.write(str(g))
   f.write("\n")
   f.write(str(h))
   f.write("\n")
   f.write(str(i))
   f.write("\n")
   f.write(str(l))
  